<?php
use App\Transverse\User;

$this->headLink()
    ->prependStylesheet('styles/bootstrap.min.css')
    ->prependStylesheet('styles/pkw.css');
$this->headScript()
    ->prependFile('js/jquery-3.4.1.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="images/pkw_logo.png" />
    <?=$this->headTitle('php kubectl web')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <?=$this->headScript()?>
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .zf-green, h2 a { color: #68b604; }
    </style>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="<?=$this->url('home')?>">
                        <img src="images/pkw_logo.png" alt="php kubectl web" height="28" />
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="https://github.com/fgsl/pkw" target="_blank" class="nav-link">
                                <i class="fa fa-book"></i> Docs
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://github.com/fgsl/pkw" target="_blank" class="nav-link">
                                <i class="fa fa-wrench"></i> Contribute
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="<?=$this->url('api.ping')?>" class="nav-link">
                                Readiness 
                            </a>
                        </li>
<?php
$user = $this->viewModel()->getCurrent()->getChildren()[0]->user;
if (!is_null($user) && $user instanceof User):
?>
                        <li class="nav-item">
                            <a href="<?=$this->url('app.logout')?>" class="nav-link">
                                Logout
                            </a>
                        </li>
<?php
endif;
?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?=$this->content?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>
                &copy; 2019 - <?=date('Y')?> FGSL.
            </p>
        </div>
    </footer>

    <?=$this->inlineScript()?>
</body>
</html>
