
<div class="col-md-8 blackbox">
	<h2>
		<i class="fa fa-bolt"></i> Create Pod
	</h2>
	<form id="form-create-pod" enctype="multipart/form-data">
		<div class="form-group">
			<label for="yaml">Yaml file</label> <input type="file"
				class="form-control" id="yaml" name="yaml"
				aria-describedby="fileHelp" placeholder="Enter file"> <small
				id="yamlHelp" class="form-text text-muted">Select a yaml file.</small>
		</div>
	</form>
	<button class="create_pod_button btn btn-primary">Create pod</button>
</div>
