
<div class="col-md-4 blackbox">
	<h2>
		<i class="fa fa-bolt"></i> Delete Pod
	</h2>
	<form id="form-delete-pod">
		<div class="form-group">
			<label for="namespace">Namespace</label> <input type="text"
				class="form-control" id="namespace" name="namespace"
				aria-describedby="namespaceHelp" placeholder="Enter namespace"> <small
				id="namespaceHelp" class="form-text text-muted">Type a namespace.</small>
		</div>
		<div class="form-group">
			<label for="namespace">Module</label> <input type="text"
				class="form-control" id="module" name="module"
				aria-describedby="moduleHelp" placeholder="Enter module"> <small
				id="moduleHelp" class="form-text text-muted">Type a module.</small>
		</div>		
	</form>	
	<button class="delete_pod_button btn btn-primary">Delete pod</button>

</div>
