<?php $this->headTitle('Home'); ?>

<div class="jumbotron">
	<h1>
		Welcome to <span class="pkw-blue">PHP Kubectl Web</span>
	</h1>
	<form action="<?=$this->url('app.login')?>" method="post">
		<div class="form-group">
			<label for="exampleInputEmail1">Username</label> <input
				type="number" class="form-control" id="username"
				aria-describedby="usernameHelp" placeholder="Enter username" autofocus="autofocus"> <small
				id="emailHelp" class="form-text text-muted">Fill this field with your username.</small>
		</div>
		<div class="form-group">
			<label for="password">Password</label> <input
				type="password" class="form-control" id="password"
				placeholder="Enter password">
		</div>
		<button type="submit" class="btn btn-primary">Login</button>
	</form>
</div>

</div>
