<?php
/**
 * PHP Kubectl Web console
 * @author Flávio Gomes da Silva Lisboa <flavio.lisboa@fgsl.eti.br>
 * @license https://www.gnu.org/licenses/lgpl-3.0.en.html
 */
use Zend\View\Helper\HeadScript;

$this->headTitle('Main page');
$script = file_get_contents(__DIR__ . '/main.js');
$this->headScript(HeadScript::SCRIPT)->appendScript($script);
?>

<div class="jumbotron">
	<h1>
		You are logged in <span class="pkw-blue">PHP Kubectl Web</span>
	</h1>

	<div class="row">
		<?php include 'detailed-partial.phtml';?>
		<?php include 'namespace-partial.phtml';?>
		<?php include 'resourcequota-partial.phtml';?>		
	</div>
	<div class="row">
		<?php include 'volumes-partial.phtml';?>
		<?php include 'replicasets-partial.phtml';?>
		<?php include 'pods-partial.phtml';?>		
	</div>

	<div class="row blackbox">
		<div id="general-result">
			<p id="paragraph-result">
				<code></code>
			</p>
		</div>
	</div>

	<div class="row">
		<?php include 'create-pods-partial.phtml';?>
        <?php include 'delete-pods-partial.phtml';?>
	</div>
</div>