<?php
use Zend\View\Helper\HeadScript;

$this->headTitle('Main page');
$this->headScript(HeadScript::SCRIPT)->appendScript('
$(document).ready(function(){
    $("button.namespace_button").click(function(){
        $( "div#namespace-result p#paragraph-result code" ).html("Wait...");
        $.post( "namespace", $("form#form-namespace").serialize() ,function( data ) {
            $( "div#namespace-result p#paragraph-result code" ).html( data.output );
        },"json");        
    });
    $("input#namespace-annotations").click(function(){
        $("input#namespace-labels").prop("checked", false);       
    });
    $("input#namespace-labels").click(function(){
        $("input#namespace-annotations").prop("checked", false);       
    });
    $("button.clear_namespace_button").click(function(){
        $( "div#namespace-result p#paragraph-result code" ).html( "" );       
    });
    $("button.resourcequota_button").click(function(){
        $( "div#resourcequota-result p#paragraph-result code" ).html("Wait...");
        $.post( "resourcequota", $("form#form-resourcequota").serialize() ,function( data ) {
            $( "div#resourcequota-result p#paragraph-result code" ).html( data.output );
        },"json");        
    });
    $("button.clear_resourcequota_button").click(function(){
        $( "div#resourcequota-result p#paragraph-result code" ).html( "" );       
    });
});
');
?>

<div class="jumbotron">
	<h1>
		You are logged in <span class="pkw-blue">PHP Kubectl Web</span>
	</h1>

	<div class="row">
		<div class="col-md-4 blackbox">
			<h2>
				<i class="fa fa-bolt"></i> Namespaces
			</h2>
			<form id="form-namespace">
				<div class="form-group">
					<label for="namespace">Namespace</label> <input type="text"
						class="form-control" id="namespace" name="namespace"
						aria-describedby="emailHelp" placeholder="Enter namespace"> <small
						id="namespaceHelp" class="form-text text-muted">Type a namespace.</small>
				</div>
				<div class="form-check">
					<input type="checkbox" class="form-check-input"
						id="namespace-object" name="namespace-object"> <label
						class="form-check-label" for="namespace-object">Complete Object</label>
				</div>
				<div class="form-check">
					<input type="checkbox" class="form-check-input"
						id="namespace-annotations" name="namespace-annotations"> <label
						class="form-check-label" for="namespace-annotations">Only
						annotations</label>
				</div>
				<div class="form-check">
					<input type="checkbox" class="form-check-input"
						id="namespace-labels" name="namespace-labels"> <label
						class="form-check-label" for="namespace-labels">Only labels</label>
				</div>
			</form>
			<button class="namespace_button btn btn-primary">Get data</button>
			<button class="clear_namespace_button btn btn-primary">Clear</button>
			<div id="namespace-result">
				<p id="paragraph-result">
					<code></code>
				</p>
			</div>
		</div>

		<div class="col-md-4 blackbox">
			<h2>
				<i class="fa fa-exchange-alt"></i> ResourceQuota
			</h2>
			<form id="form-resourcequota">
				<div class="form-group">
					<label for="namespace">Namespace</label> <input type="text"
						class="form-control" id="namespace" name="namespace"
						aria-describedby="emailHelp" placeholder="Enter namespace"> <small
						id="namespaceHelp" class="form-text text-muted">Type a namespace.</small>
				</div>
				<div class="form-check">
					<input type="checkbox" class="form-check-input"
						id="resourcequota-object" name="resourcequota-object"> <label
						class="form-check-label" for="resourcequota-object">Complete
						object</label>
				</div>
			</form>
			<button class="resourcequota_button btn btn-primary">Get data</button>
			<button class="clear_resourcequota_button btn btn-primary">Clear</button>
			<div id="resourcequota-result">
				<p id="paragraph-result">
					<code></code>
				</p>
			</div>
		</div>

	</div>

</div>
