<div class="col-md-4 blackbox">
	<h2>
		<i class="fa fa-bolt"></i> Namespaces
	</h2>
	<form id="form-namespace">
		<div class="form-group">
			<label for="namespace">Namespace</label> <input type="text"
				class="form-control" id="namespace" name="namespace"
				aria-describedby="namespaceHelp" placeholder="Enter namespace"> <small
				id="namespaceHelp" class="form-text text-muted">Type a namespace.</small>
		</div>
		<div class="form-check">
			<input type="checkbox" class="form-check-input" id="namespace-object"
				name="namespace-object"> <label class="form-check-label"
				for="namespace-object">Complete Object</label>
		</div>
		<div class="form-check">
			<input type="checkbox" class="form-check-input"
				id="namespace-annotations" name="namespace-annotations"> <label
				class="form-check-label" for="namespace-annotations">Only
				annotations</label>
		</div>
		<div class="form-check">
			<input type="checkbox" class="form-check-input" id="namespace-labels"
				name="namespace-labels"> <label class="form-check-label"
				for="namespace-labels">Only labels</label>
		</div>
	</form>
	<button class="namespace_button btn btn-primary">Get data</button>
	<button class="clear_result_button btn btn-primary">Clear</button>
</div>