
<div class="col-md-4 blackbox">
	<h2>
		<i class="fa fa-bolt"></i> Pods
	</h2>
	<form id="form-pods">
		<div class="form-group">
			<label for="namespace">Namespace</label> <input type="text"
				class="form-control" id="namespace" name="namespace"
				aria-describedby="namespaceHelp" placeholder="Enter namespace"> <small
				id="namespaceHelp" class="form-text text-muted">Type a namespace.</small>
		</div>
		<div class="form-check">
			<input type="checkbox" class="form-check-input" id="pods-object"
				name="pods-object"> <label class="form-check-label"
				for="pods-object">Complete Object</label>
		</div>
		<div class="form-check">
			<input type="checkbox" class="form-check-input" id="pods-labels"
				name="pods-labels"> <label class="form-check-label"
				for="namespace-labels">Show labels</label>
		</div>
	</form>
	<button class="pods_button btn btn-primary">Get data</button>
	<button class="clear_result_button btn btn-primary">Clear</button>
</div>
