<div class="col-md-4 blackbox">
	<h2>
		<i class="fa fa-exchange-alt"></i>Volumes
	</h2>
	<form id="form-volumes">
		<div class="form-group">
			<label for="namespace">Namespace</label> <input type="text"
				class="form-control" id="namespace" name="namespace"
				aria-describedby="emailNamespace" placeholder="Enter namespace"> <small
				id="namespaceHelp" class="form-text text-muted">Type a namespace.</small>
		</div>
		<div class="form-check">
			<input type="checkbox" class="form-check-input"
				id="volumes-object" name="volumes-object"> <label
				class="form-check-label" for="volumes-object">Complete object</label>
		</div>
	</form>
	<button class="volumes_button btn btn-primary">Get data</button>
	<button class="clear_result_button btn btn-primary">Clear</button>
</div>